[package]
name = "craft"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
cfb8 = "0.8.1"
rand = "0.8"
rsa = "0.9.8"
rsa-der = "0.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.16"
tracing = { version = "0.1.41", features = ["attributes"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
uuid = { version = "1.18.1", features = ["v4"] }
